import { prisma as Prisma } from "@/lib/prisma";
import { randomUUID } from "crypto";
import { hashPassword } from "better-auth/crypto";

export const usersData = [
  // Enseignants
  {
    username: "prof.mukendi",
    email: "mukendi@eteyelo.cd",
    telephone: "+243812345601",
    nom: "Mukendi",
    postnom: "Kabongo",
    prenom: "Jean",
    dateOfBirth: new Date("1985-03-15"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },
  {
    username: "prof.mbuyi",
    email: "mbuyi@eteyelo.cd",
    telephone: "+243812345602",
    nom: "Mbuyi",
    postnom: "Kalala",
    prenom: "Marie",
    dateOfBirth: new Date("1990-07-22"),
    sexe: "F",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },
  {
    username: "prof.tshimanga",
    email: "tshimanga@eteyelo.cd",
    telephone: "+243812345603",
    nom: "Tshimanga",
    postnom: "Mutombo",
    prenom: "Pierre",
    dateOfBirth: new Date("1982-11-08"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },
  {
    username: "prof.ndaya",
    email: "ndaya@eteyelo.cd",
    telephone: "+243812345604",
    nom: "Ndaya",
    postnom: "Kilolo",
    prenom: "Brigitte",
    dateOfBirth: new Date("1988-01-30"),
    sexe: "F",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },
  {
    username: "prof.kabila",
    email: "kabila@eteyelo.cd",
    telephone: "+243812345605",
    nom: "Kabila",
    postnom: "Mwamba",
    prenom: "Joseph",
    dateOfBirth: new Date("1979-05-12"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },
  {
    username: "prof.mpiana",
    email: "mpiana@eteyelo.cd",
    telephone: "+243812345606",
    nom: "Mpiana",
    postnom: "Tshisekedi",
    prenom: "Antoinette",
    dateOfBirth: new Date("1987-09-18"),
    sexe: "F",
    password: "Password123!",
    statusUser: true,
    userType: "teacher" as const,
  },

  // Parents
  {
    username: "parent.kasongo",
    email: "kasongo@parent.cd",
    telephone: "+243812345701",
    nom: "Kasongo",
    postnom: "Mwanza",
    prenom: "André",
    dateOfBirth: new Date("1975-04-20"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "parent" as const,
  },
  {
    username: "parent.kalombo",
    email: "kalombo@parent.cd",
    telephone: "+243812345702",
    nom: "Kalombo",
    postnom: "Ngoy",
    prenom: "Thérèse",
    dateOfBirth: new Date("1978-08-14"),
    sexe: "F",
    password: "Password123!",
    statusUser: true,
    userType: "parent" as const,
  },
  {
    username: "parent.mulumba",
    email: "mulumba@parent.cd",
    telephone: "+243812345703",
    nom: "Mulumba",
    postnom: "Kabongo",
    prenom: "François",
    dateOfBirth: new Date("1972-12-05"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "parent" as const,
  },
  {
    username: "parent.mwamba",
    email: "mwamba@parent.cd",
    telephone: "+243812345704",
    nom: "Mwamba",
    postnom: "Lukoji",
    prenom: "Clémentine",
    dateOfBirth: new Date("1980-02-28"),
    sexe: "F",
    password: "Password123!",
    statusUser: true,
    userType: "parent" as const,
  },
  {
    username: "parent.katanga",
    email: "katanga@parent.cd",
    telephone: "+243812345705",
    nom: "Katanga",
    postnom: "Mujinga",
    prenom: "Daniel",
    dateOfBirth: new Date("1976-06-10"),
    sexe: "M",
    password: "Password123!",
    statusUser: true,
    userType: "parent" as const,
  },

  // Élèves
  {
    username: "eleve.kasongo.junior",
    email: "kasongo.junior@eleve.cd",
    telephone: "+243812345801",
    nom: "Kasongo",
    postnom: "Mwanza",
    prenom: "Junior",
    dateOfBirth: new Date("2007-03-15"),
    sexe: "M",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.kalombo.grâce",
    email: "kalombo.grace@eleve.cd",
    telephone: "+243812345802",
    nom: "Kalombo",
    postnom: "Ngoy",
    prenom: "Grâce",
    dateOfBirth: new Date("2008-01-22"),
    sexe: "F",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.mulumba.prince",
    email: "mulumba.prince@eleve.cd",
    telephone: "+243812345803",
    nom: "Mulumba",
    postnom: "Kabongo",
    prenom: "Prince",
    dateOfBirth: new Date("2007-11-08"),
    sexe: "M",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.mwamba.esther",
    email: "mwamba.esther@eleve.cd",
    telephone: "+243812345804",
    nom: "Mwamba",
    postnom: "Lukoji",
    prenom: "Esther",
    dateOfBirth: new Date("2008-05-30"),
    sexe: "F",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.katanga.david",
    email: "katanga.david@eleve.cd",
    telephone: "+243812345805",
    nom: "Katanga",
    postnom: "Mujinga",
    prenom: "David",
    dateOfBirth: new Date("2007-09-12"),
    sexe: "M",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.mukendi.sarah",
    email: "mukendi.sarah@eleve.cd",
    telephone: "+243812345806",
    nom: "Mukendi",
    postnom: "Kabamba",
    prenom: "Sarah",
    dateOfBirth: new Date("2008-07-18"),
    sexe: "F",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.tshiamala.michel",
    email: "tshiamala.michel@eleve.cd",
    telephone: "+243812345807",
    nom: "Tshiamala",
    postnom: "Ngalula",
    prenom: "Michel",
    dateOfBirth: new Date("2007-12-25"),
    sexe: "M",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.kabongo.ruth",
    email: "kabongo.ruth@eleve.cd",
    telephone: "+243812345808",
    nom: "Kabongo",
    postnom: "Mputu",
    prenom: "Ruth",
    dateOfBirth: new Date("2008-04-03"),
    sexe: "F",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.mputu.samuel",
    email: "mputu.samuel@eleve.cd",
    telephone: "+243812345809",
    nom: "Mputu",
    postnom: "Kasadi",
    prenom: "Samuel",
    dateOfBirth: new Date("2007-08-14"),
    sexe: "M",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },
  {
    username: "eleve.tshilombo.joie",
    email: "tshilombo.joie@eleve.cd",
    telephone: "+243812345810",
    nom: "Tshilombo",
    postnom: "Kapinga",
    prenom: "Joie",
    dateOfBirth: new Date("2008-10-07"),
    sexe: "F",
    password: "Student123!",
    statusUser: true,
    userType: "student" as const,
  },

  // Administrateur
  {
    username: "admin",
    email: "admin@eteyelo.cd",
    telephone: "+243812345900",
    nom: "Administrateur",
    postnom: "Système",
    prenom: "Admin",
    dateOfBirth: new Date("1980-01-01"),
    sexe: "M",
    password: "Admin123!",
    statusUser: true,
    userType: "admin" as const,
  },
];

export async function initUsers() {
  console.log("👥 Initialisation des utilisateurs...");

  for (const userData of usersData) {
    const hashedPassword = await hashPassword(userData.password);
    const name = `${userData.prenom} ${userData.postnom} ${userData.nom}`;
    const role = userData.userType === "admin" ? "admin" : "user";

    const user = await Prisma.user.upsert({
      where: { username: userData.username },
      update: {
        name,
        email: userData.email,
        telephone: userData.telephone,
        postnom: userData.postnom,
        prenom: userData.prenom,
        dateOfBirth: userData.dateOfBirth,
        sexe: userData.sexe,
        statusUser: userData.statusUser,
        role,
      },
      create: {
        username: userData.username,
        name,
        email: userData.email,
        telephone: userData.telephone,
        postnom: userData.postnom,
        prenom: userData.prenom,
        dateOfBirth: userData.dateOfBirth,
        sexe: userData.sexe,
        statusUser: userData.statusUser,
        role,
        emailVerified: true,
      },
    });

    const existingAccount = await Prisma.account.findFirst({
      where: {
        userId: user.id,
        providerId: "credential",
      },
    });

    if (existingAccount) {
      await Prisma.account.update({
        where: { id: existingAccount.id },
        data: {
          accountId: user.id,
          password: hashedPassword,
          updatedAt: new Date(),
        },
      });
    } else {
      await Prisma.account.create({
        data: {
          id: randomUUID(),
          accountId: user.id,
          providerId: "credential",
          userId: user.id,
          password: hashedPassword,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      });
    }
  }

  console.log(`✅ ${usersData.length} utilisateurs créés`);
}

export async function clearUsers() {
  console.log("🗑️  Suppression des utilisateurs...");
  await Prisma.user.deleteMany({});
  console.log("✅ Utilisateurs supprimés");
}
