import { Section } from "./types";

export function getSections(): Section[] {
  const sections: Section[] = [
    {
      title: "SOCIAL STUDIES",
      subjects: [
        {
          name: "Christian Education",
          max1: "10",
          gs1: "",
          bl1: "7",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Citizenship",
          max1: "10",
          gs1: "",
          bl1: "10",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Geography",
          max1: "10",
          gs1: "",
          bl1: "10",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "History",
          max1: "10",
          gs1: "",
          bl1: "6",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Science",
          max1: "10",
          gs1: "",
          bl1: "10",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Health Education",
          max1: "10",
          gs1: "",
          bl1: "7",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Handwriting",
          max1: "10",
          gs1: "",
          bl1: "8",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Art/Music",
          max1: "10",
          gs1: "",
          bl1: "10",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Physical Ed",
          max1: "10",
          gs1: "",
          bl1: "8",
          max2: "10",
          gs2: "",
          bl2: "10",
          max3: "10",
          gs3: "",
          bl3: "10",
        },
        {
          name: "Ict .",
          max1: "10",
          gs1: "",
          bl1: "8",
          max2: "10",
          gs2: "",
          bl2: "9",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
      ],
    },

    {
      title: "ENGLISH LANGUAGE ARTS",
      subjects: [
        {
          name: "Reading",
          max1: "10",
          gs1: "",
          bl1: "10",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Vocabulary",
          max1: "10",
          gs1: "",
          bl1: "0",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Spelling/Dictation",
          max1: "10",
          gs1: "",
          bl1: "0",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Elocution/Speech",
          max1: "10",
          gs1: "",
          bl1: "0",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Conjugation",
          max1: "10",
          gs1: "",
          bl1: "0",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Recitation",
          max1: "10",
          gs1: "",
          bl1: "0",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Grammar",
          max1: "10",
          gs1: "",
          bl1: "8",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Writing",
          max1: "10",
          gs1: "",
          bl1: "7",
          max2: "10",
          gs2: "",
          bl2: "0",
          max3: "10",
          gs3: "",
          bl3: "0",
        },
      ],
    },

    {
      title: "MATHEMATICS",
      subjects: [
        {
          name: "Maths",
          max1: "100",
          gs1: "",
          bl1: "50",
          max2: "100",
          gs2: "",
          bl2: "0",
          max3: "100",
          gs3: "",
          bl3: "0",
        },
      ],
    },

    {
      title: "",
      subjects: [
        {
          name: "Max Total",
          max1: "0",
          gs1: "",
          bl1: "0",
          max2: "0",
          gs2: "8",
          bl2: "0",
          max3: "0",
          gs3: "",
          bl3: "0",
        },
        {
          name: "Percentage",
          max1: "",
          gs1: "",
          bl1: "",
          max2: "",
          gs2: "",
          bl2: "",
          max3: "",
          gs3: "",
          bl3: "",
        },
      ],
    },

    {
      title: "SIGNATURES",
      subjects: [],
    },
  ];

  return sections;
}
export function getAttendance() {
  return {
    attendanceRows: [
      {
        label: "DAYS PRESENT",
        value1: "53",
        value2: "53",
      },
      {
        label: "DAYS ABSENT",
        value1: "0",
        value2: "0",
      },
      {
        label: "BEHAVIOR",
        value1: "V G",
        value2: "VG",
      },
    ],
  };
}
export function getGradeScale() {
  return {
    gradeRows: [
      {
        scale: "90% to 100%",
        descriptor: "A",
      },
      {
        scale: "80% to 89%",
        descriptor: "B",
      },
      {
        scale: "70% to 79%",
        descriptor: "C",
      },
      {
        scale: "60% to 69%",
        descriptor: "D",
      },
      {
        scale: "55% to 59%",
        descriptor: "E",
      },
      {
        scale: "0% to 54%",
        descriptor: "F",
      },
    ],
  };
}

  

